version: 0.2

phases:
  pre_build:
    commands:
      - echo "Iniciando sesión en ECR..."
      - aws --version
      - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI)
      - echo "Definiendo etiqueta de imagen..."
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo "Construyendo imagen Docker usando deployment/Dockerfile.deploy..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG -f deployment/Dockerfile.deploy .
  post_build:
    commands:
      - echo "Pusheando la imagen a ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name": "imageUri", "value": "%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json

artifacts:
  files:
    - imageDetail.json

