services:
  db:
    image: postgres:15
    env_file:
      - ./.envs/.env.postgres
    ports:
      - 5440:5432
    networks:
      - "local-development"
  tests:
    build:
      dockerfile: deployment/Dockerfile.test
    env_file:
      - ./.envs/.env.base
      - ./.envs/.env.test
    ports:
      - 9001:9000
    networks:
      - "local-development"
    depends_on:
      - db
  app:
    build:
      dockerfile: deployment/Dockerfile.deploy
    environment:
      - ENVIRONMENT=docker
    env_file:
      - ./.envs/.env.docker
    ports:
      - 9001:9000
    networks:
      - "local-development"
    depends_on:
      - db
networks:
  local-development:
