services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: unicon
    ports:
      - 5441:5432
    networks:
      - "local-development"
  db-mysql:
      image: mysql:8
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: jalo
      ports:
        - 3306:3306
      networks:
        - "local-development"
  tests:
    build:
      dockerfile: deployment/Dockerfile.test
    env_file:
      - ./.envs/.env.base
      - ./.envs/.env.test
    ports:
      - 9001:9000
    networks:
      - "local-development"
    depends_on:
      - db
  app:
    build:
      dockerfile: deployment/Dockerfile.deploy
    environment:
      - ENVIRONMENT=development
    env_file:
      - ./.envs/.env.dev
    ports:
      - 9001:9000
    networks:
      - "local-development"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "512m"

  queue:
    image: rabbitmq:3-management
    ports:
      - "5673:5672" # Puerto para aplicaciones
      - "15673:15672" # Puerto para la interfaz de administración
    environment:
      RABBITMQ_DEFAULT_USER: admin # Usuario por defecto
      RABBITMQ_DEFAULT_PASS: password # Contraseña por defecto

networks:
  local-development:
