name: Linter

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U ruff

    - name: Run ruff
      run: ruff check .
