name: Testing

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  testing:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install System dependencies
        run: |
          pip install --upgrade pip
          pip install -U poetry

      - name: Install Project dependencies
        run: |
          poetry install --no-root
          pip install coverage pytest

      - name: Run tests
        run: |
          rm -rf reports && mkdir reports
          coverage run -m pytest -s -v --lf --junitxml=reports/unittest_report.xml
